// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * Body_login-login_access_token
 */
export type BodyLoginLoginAccessToken = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * CompetitionPublic
 */
export type CompetitionPublic = {
    /**
     * Match Updated
     */
    match_updated?: string | null;
    /**
     * Match Available
     */
    match_available?: string | null;
    /**
     * Match Updated 360
     */
    match_updated_360?: string | null;
    /**
     * Match Available 360
     */
    match_available_360?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Country Name
     */
    country_name: string;
    /**
     * Competition Name
     */
    competition_name: string;
    /**
     * Competition Gender
     */
    competition_gender: string;
    /**
     * Competition Youth
     */
    competition_youth?: boolean;
    /**
     * Competition International
     */
    competition_international?: boolean;
    /**
     * Season Name
     */
    season_name: string;
    /**
     * Match Count
     */
    match_count?: number;
    /**
     * Event Match Count
     */
    event_match_count?: number;
    /**
     * Has Events
     */
    has_events?: boolean;
};

/**
 * CompetitionsPublic
 */
export type CompetitionsPublic = {
    /**
     * Data
     */
    data: Array<CompetitionPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * EventPublic
 */
export type EventPublic = {
    /**
     * Statsbomb Id
     */
    statsbomb_id: string;
    /**
     * Match Id
     */
    match_id: string;
    /**
     * Index
     */
    index: number;
    /**
     * Period
     */
    period: number;
    /**
     * Timestamp
     */
    timestamp?: string | null;
    /**
     * Minute
     */
    minute: number;
    /**
     * Second
     */
    second: number;
    /**
     * Type Name
     */
    type_name: string;
    /**
     * Possession
     */
    possession?: number | null;
    /**
     * Play Pattern Name
     */
    play_pattern_name?: string | null;
    /**
     * Location X
     */
    location_x?: number | null;
    /**
     * Location Y
     */
    location_y?: number | null;
    /**
     * End Location X
     */
    end_location_x?: number | null;
    /**
     * End Location Y
     */
    end_location_y?: number | null;
    /**
     * Duration
     */
    duration?: number | null;
    /**
     * Under Pressure
     */
    under_pressure?: boolean | null;
    /**
     * Off Camera
     */
    off_camera?: boolean | null;
    /**
     * Out
     */
    out?: boolean | null;
    /**
     * Id
     */
    id: string;
    /**
     * Team
     */
    team: string;
    /**
     * Player
     */
    player?: string | null;
    /**
     * Pass Recipient
     */
    pass_recipient?: string | null;
    /**
     * Possession Team Name
     */
    possession_team_name?: string | null;
};

/**
 * EventsPublic
 */
export type EventsPublic = {
    /**
     * Data
     */
    data: Array<EventPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * Frame360Public
 */
export type Frame360Public = {
    /**
     * Match Id
     */
    match_id: string;
    /**
     * Event Statsbomb Id
     */
    event_statsbomb_id: string;
    /**
     * Visible Area
     */
    visible_area?: Array<unknown>;
    /**
     * Freeze Frame
     */
    freeze_frame?: Array<unknown>;
    /**
     * Id
     */
    id: string;
};

/**
 * Frames360Public
 */
export type Frames360Public = {
    /**
     * Data
     */
    data: Array<Frame360Public>;
    /**
     * Count
     */
    count: number;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * IngestResult
 */
export type IngestResult = {
    /**
     * Imported Competitions
     */
    imported_competitions: number;
    /**
     * Imported Matches
     */
    imported_matches: number;
};

/**
 * LineupPublic
 */
export type LineupPublic = {
    /**
     * Match Id
     */
    match_id: string;
    /**
     * Statsbomb Player Id
     */
    statsbomb_player_id: number;
    /**
     * Jersey Number
     */
    jersey_number: number;
    /**
     * Started
     */
    started?: boolean;
    /**
     * Id
     */
    id: string;
    /**
     * Team Name
     */
    team_name: string;
    /**
     * Player Name
     */
    player_name: string;
    /**
     * Player Nickname
     */
    player_nickname?: string | null;
    /**
     * Country Name
     */
    country_name?: string | null;
};

/**
 * LineupsPublic
 */
export type LineupsPublic = {
    /**
     * Data
     */
    data: Array<LineupPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * NewPassword
 */
export type NewPassword = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * PlayerPublic
 */
export type PlayerPublic = {
    /**
     * Statsbomb Id
     */
    statsbomb_id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Nickname
     */
    nickname?: string | null;
    /**
     * Nationality
     */
    nationality?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Match Count
     */
    match_count?: number;
};

/**
 * PlayerSeasonStats
 *
 * Appearances, minutes and per-90 event rates for one player.
 */
export type PlayerSeasonStats = {
    /**
     * Player Id
     */
    player_id: string;
    /**
     * Player Name
     */
    player_name: string;
    /**
     * Season Id
     */
    season_id?: string | null;
    /**
     * Appearances
     */
    appearances: number;
    /**
     * Minutes Played
     */
    minutes_played: number;
    /**
     * Stats
     */
    stats: Array<PlayerStatLine>;
};

/**
 * PlayerStatLine
 *
 * One event type and how often the player produced it.
 */
export type PlayerStatLine = {
    /**
     * Type Name
     */
    type_name: string;
    /**
     * Count
     */
    count: number;
    /**
     * Per 90
     */
    per_90: number;
};

/**
 * PlayersPublic
 */
export type PlayersPublic = {
    /**
     * Data
     */
    data: Array<PlayerPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * PrivateUserCreate
 */
export type PrivateUserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Is Verified
     */
    is_verified?: boolean;
};

/**
 * SoccerMatchPublic
 */
export type SoccerMatchPublic = {
    /**
     * Statsbomb Id
     */
    statsbomb_id: number;
    /**
     * Competition Season Id
     */
    competition_season_id: string;
    /**
     * Match Date
     */
    match_date: string;
    /**
     * Kick Off
     */
    kick_off?: string | null;
    /**
     * Home Score
     */
    home_score?: number | null;
    /**
     * Away Score
     */
    away_score?: number | null;
    /**
     * Stadium
     */
    stadium?: string | null;
    /**
     * Referee
     */
    referee?: string | null;
    /**
     * Match Week
     */
    match_week?: number | null;
    /**
     * Competition Stage Name
     */
    competition_stage_name?: string | null;
    /**
     * Home Team Gender
     */
    home_team_gender?: string | null;
    /**
     * Away Team Gender
     */
    away_team_gender?: string | null;
    /**
     * Home Team Country Name
     */
    home_team_country_name?: string | null;
    /**
     * Away Team Country Name
     */
    away_team_country_name?: string | null;
    /**
     * Home Team Group
     */
    home_team_group?: string | null;
    /**
     * Away Team Group
     */
    away_team_group?: string | null;
    /**
     * Home Manager Name
     */
    home_manager_name?: string | null;
    /**
     * Away Manager Name
     */
    away_manager_name?: string | null;
    /**
     * Match Status
     */
    match_status?: string | null;
    /**
     * Last Updated
     */
    last_updated?: string | null;
    /**
     * Match Status 360
     */
    match_status_360?: string | null;
    /**
     * Home Team Id
     */
    home_team_id: string;
    /**
     * Away Team Id
     */
    away_team_id: string;
    /**
     * Id
     */
    id: string;
    /**
     * Home Team
     */
    home_team: string;
    /**
     * Away Team
     */
    away_team: string;
    /**
     * Has Events
     */
    has_events?: boolean;
};

/**
 * SoccerMatchesPublic
 */
export type SoccerMatchesPublic = {
    /**
     * Data
     */
    data: Array<SoccerMatchPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * SoccerTeamsPublic
 */
export type SoccerTeamsPublic = {
    /**
     * Data
     */
    data: Array<string>;
};

/**
 * StatsBombCompetition
 */
export type StatsBombCompetition = {
    /**
     * Competition Id
     */
    competition_id: number;
    /**
     * Competition Name
     */
    competition_name: string;
    /**
     * Country Name
     */
    country_name: string;
    /**
     * Season Id
     */
    season_id: number;
    /**
     * Season Name
     */
    season_name: string;
    /**
     * Has 360
     */
    has_360: boolean;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * UserRegister
 */
export type UserRegister = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name?: string | null;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password?: string | null;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * UsersPublic
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type LoginLoginAccessTokenData = {
    body: BodyLoginLoginAccessToken;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type LoginLoginAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginLoginAccessTokenError = LoginLoginAccessTokenErrors[keyof LoginLoginAccessTokenErrors];

export type LoginLoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type LoginLoginAccessTokenResponse = LoginLoginAccessTokenResponses[keyof LoginLoginAccessTokenResponses];

export type LoginTestTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/test-token';
};

export type LoginTestTokenResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type LoginTestTokenResponse = LoginTestTokenResponses[keyof LoginTestTokenResponses];

export type LoginRecoverPasswordData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery/{email}';
};

export type LoginRecoverPasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginRecoverPasswordError = LoginRecoverPasswordErrors[keyof LoginRecoverPasswordErrors];

export type LoginRecoverPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type LoginRecoverPasswordResponse = LoginRecoverPasswordResponses[keyof LoginRecoverPasswordResponses];

export type LoginResetPasswordData = {
    body: NewPassword;
    path?: never;
    query?: never;
    url: '/api/v1/reset-password/';
};

export type LoginResetPasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginResetPasswordError = LoginResetPasswordErrors[keyof LoginResetPasswordErrors];

export type LoginResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type LoginResetPasswordResponse = LoginResetPasswordResponses[keyof LoginResetPasswordResponses];

export type LoginRecoverPasswordHtmlContentData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery-html-content/{email}';
};

export type LoginRecoverPasswordHtmlContentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginRecoverPasswordHtmlContentError = LoginRecoverPasswordHtmlContentErrors[keyof LoginRecoverPasswordHtmlContentErrors];

export type LoginRecoverPasswordHtmlContentResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type LoginRecoverPasswordHtmlContentResponse = LoginRecoverPasswordHtmlContentResponses[keyof LoginRecoverPasswordHtmlContentResponses];

export type UsersReadUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/users/';
};

export type UsersReadUsersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersReadUsersError = UsersReadUsersErrors[keyof UsersReadUsersErrors];

export type UsersReadUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type UsersReadUsersResponse = UsersReadUsersResponses[keyof UsersReadUsersResponses];

export type UsersCreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type UsersCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersCreateUserError = UsersCreateUserErrors[keyof UsersCreateUserErrors];

export type UsersCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersCreateUserResponse = UsersCreateUserResponses[keyof UsersCreateUserResponses];

export type UsersDeleteUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersDeleteUserMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersDeleteUserMeResponse = UsersDeleteUserMeResponses[keyof UsersDeleteUserMeResponses];

export type UsersReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersReadUserMeResponse = UsersReadUserMeResponses[keyof UsersReadUserMeResponses];

export type UsersUpdateUserMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersUpdateUserMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdateUserMeError = UsersUpdateUserMeErrors[keyof UsersUpdateUserMeErrors];

export type UsersUpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersUpdateUserMeResponse = UsersUpdateUserMeResponses[keyof UsersUpdateUserMeResponses];

export type UsersUpdatePasswordMeData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type UsersUpdatePasswordMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdatePasswordMeError = UsersUpdatePasswordMeErrors[keyof UsersUpdatePasswordMeErrors];

export type UsersUpdatePasswordMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersUpdatePasswordMeResponse = UsersUpdatePasswordMeResponses[keyof UsersUpdatePasswordMeResponses];

export type UsersRegisterUserData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/users/signup';
};

export type UsersRegisterUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersRegisterUserError = UsersRegisterUserErrors[keyof UsersRegisterUserErrors];

export type UsersRegisterUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersRegisterUserResponse = UsersRegisterUserResponses[keyof UsersRegisterUserResponses];

export type UsersDeleteUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersDeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersDeleteUserError = UsersDeleteUserErrors[keyof UsersDeleteUserErrors];

export type UsersDeleteUserResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersDeleteUserResponse = UsersDeleteUserResponses[keyof UsersDeleteUserResponses];

export type UsersReadUserByIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersReadUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersReadUserByIdError = UsersReadUserByIdErrors[keyof UsersReadUserByIdErrors];

export type UsersReadUserByIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersReadUserByIdResponse = UsersReadUserByIdResponses[keyof UsersReadUserByIdResponses];

export type UsersUpdateUserData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersUpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdateUserError = UsersUpdateUserErrors[keyof UsersUpdateUserErrors];

export type UsersUpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersUpdateUserResponse = UsersUpdateUserResponses[keyof UsersUpdateUserResponses];

export type UtilsTestEmailData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Email To
         */
        email_to: string;
    };
    url: '/api/v1/utils/test-email/';
};

export type UtilsTestEmailErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UtilsTestEmailError = UtilsTestEmailErrors[keyof UtilsTestEmailErrors];

export type UtilsTestEmailResponses = {
    /**
     * Successful Response
     */
    201: Message;
};

export type UtilsTestEmailResponse = UtilsTestEmailResponses[keyof UtilsTestEmailResponses];

export type UtilsHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check/';
};

export type UtilsHealthCheckResponses = {
    /**
     * Response Utils-Health Check
     *
     * Successful Response
     */
    200: boolean;
};

export type UtilsHealthCheckResponse = UtilsHealthCheckResponses[keyof UtilsHealthCheckResponses];

export type ReadCompetitionsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Has Matches
         */
        has_matches?: boolean;
        /**
         * Has Events
         */
        has_events?: boolean;
    };
    url: '/api/v1/soccer/competitions/';
};

export type ReadCompetitionsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadCompetitionsError = ReadCompetitionsErrors[keyof ReadCompetitionsErrors];

export type ReadCompetitionsResponses = {
    /**
     * Successful Response
     */
    200: CompetitionsPublic;
};

export type ReadCompetitionsResponse = ReadCompetitionsResponses[keyof ReadCompetitionsResponses];

export type IngestSoccerDataData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/soccer/competitions/ingest';
};

export type IngestSoccerDataResponses = {
    /**
     * Successful Response
     */
    200: IngestResult;
};

export type IngestSoccerDataResponse = IngestSoccerDataResponses[keyof IngestSoccerDataResponses];

export type GetAvailableCompetitionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/soccer/competitions/available';
};

export type GetAvailableCompetitionsResponses = {
    /**
     * Response Getavailablecompetitions
     *
     * Successful Response
     */
    200: Array<StatsBombCompetition>;
};

export type GetAvailableCompetitionsResponse = GetAvailableCompetitionsResponses[keyof GetAvailableCompetitionsResponses];

export type ReadMatchesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Competition Season Id
         */
        competition_season_id?: string | null;
        /**
         * Has Events
         */
        has_events?: boolean;
        /**
         * Team Name
         */
        team_name?: string | null;
        /**
         * Team Id
         */
        team_id?: string | null;
    };
    url: '/api/v1/soccer/matches/';
};

export type ReadMatchesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadMatchesError = ReadMatchesErrors[keyof ReadMatchesErrors];

export type ReadMatchesResponses = {
    /**
     * Successful Response
     */
    200: SoccerMatchesPublic;
};

export type ReadMatchesResponse = ReadMatchesResponses[keyof ReadMatchesResponses];

export type ReadMatchTeamsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Competition Season Id
         */
        competition_season_id?: string | null;
        /**
         * Has Events
         */
        has_events?: boolean;
    };
    url: '/api/v1/soccer/matches/teams';
};

export type ReadMatchTeamsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadMatchTeamsError = ReadMatchTeamsErrors[keyof ReadMatchTeamsErrors];

export type ReadMatchTeamsResponses = {
    /**
     * Successful Response
     */
    200: SoccerTeamsPublic;
};

export type ReadMatchTeamsResponse = ReadMatchTeamsResponses[keyof ReadMatchTeamsResponses];

export type ReadEventsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Match Id
         */
        match_id: string;
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Type Name
         */
        type_name?: string | null;
        /**
         * Team
         */
        team?: string | null;
        /**
         * Period
         */
        period?: number | null;
        /**
         * Player
         */
        player?: string | null;
        /**
         * Possession
         */
        possession?: number | null;
        /**
         * Team Id
         */
        team_id?: string | null;
    };
    url: '/api/v1/soccer/events/';
};

export type ReadEventsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadEventsError = ReadEventsErrors[keyof ReadEventsErrors];

export type ReadEventsResponses = {
    /**
     * Successful Response
     */
    200: EventsPublic;
};

export type ReadEventsResponse = ReadEventsResponses[keyof ReadEventsResponses];

export type IngestEventsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Competition Statsbomb Id
         */
        competition_statsbomb_id?: number;
        /**
         * Season Id
         */
        season_id?: number;
    };
    url: '/api/v1/soccer/events/ingest';
};

export type IngestEventsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type IngestEventsError = IngestEventsErrors[keyof IngestEventsErrors];

export type IngestEventsResponses = {
    /**
     * Response Ingestevents
     *
     * Successful Response
     */
    202: {
        [key: string]: string;
    };
};

export type IngestEventsResponse = IngestEventsResponses[keyof IngestEventsResponses];

export type ReadLineupsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Match Id
         */
        match_id: string;
    };
    url: '/api/v1/soccer/lineups/';
};

export type ReadLineupsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadLineupsError = ReadLineupsErrors[keyof ReadLineupsErrors];

export type ReadLineupsResponses = {
    /**
     * Successful Response
     */
    200: LineupsPublic;
};

export type ReadLineupsResponse = ReadLineupsResponses[keyof ReadLineupsResponses];

export type ReadFramesData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Match Id
         */
        match_id: string;
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/soccer/frames/';
};

export type ReadFramesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadFramesError = ReadFramesErrors[keyof ReadFramesErrors];

export type ReadFramesResponses = {
    /**
     * Successful Response
     */
    200: Frames360Public;
};

export type ReadFramesResponse = ReadFramesResponses[keyof ReadFramesResponses];

export type ReadPlayersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Name Search
         */
        name_search?: string | null;
    };
    url: '/api/v1/soccer/players/';
};

export type ReadPlayersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadPlayersError = ReadPlayersErrors[keyof ReadPlayersErrors];

export type ReadPlayersResponses = {
    /**
     * Successful Response
     */
    200: PlayersPublic;
};

export type ReadPlayersResponse = ReadPlayersResponses[keyof ReadPlayersResponses];

export type ReadPlayerSeasonStatsData = {
    body?: never;
    path: {
        /**
         * Player Id
         */
        player_id: string;
    };
    query?: {
        /**
         * Season Id
         */
        season_id?: string | null;
    };
    url: '/api/v1/soccer/players/{player_id}/stats';
};

export type ReadPlayerSeasonStatsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadPlayerSeasonStatsError = ReadPlayerSeasonStatsErrors[keyof ReadPlayerSeasonStatsErrors];

export type ReadPlayerSeasonStatsResponses = {
    /**
     * Successful Response
     */
    200: PlayerSeasonStats;
};

export type ReadPlayerSeasonStatsResponse = ReadPlayerSeasonStatsResponses[keyof ReadPlayerSeasonStatsResponses];

export type PrivateCreateUserData = {
    body: PrivateUserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/private/users/';
};

export type PrivateCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PrivateCreateUserError = PrivateCreateUserErrors[keyof PrivateCreateUserErrors];

export type PrivateCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type PrivateCreateUserResponse = PrivateCreateUserResponses[keyof PrivateCreateUserResponses];
