"""drop legacy StatsBomb ints and rename season_ref_id -> season_id (issue #40)

Revision ID: 3a71c4e9d052
Revises: 9f3f8d81b1e1
Create Date: 2026-09-05 12:45:00.000000

Phase 2 split `competition` into `competition` x `season` -> `competition_season`,
and the edition's season FK had to be called `season_ref_id` because the name
`season_id` was still taken by StatsBomb's own integer season id. This drops
the two duplicated integers and frees the name.

**Nothing is lost.** Both values already live on the rows that own them —
`competition.external_id` and `season.external_id` — and were verified
identical for every edition before the drop:

    SELECT count(*) FROM competition_season cs
    JOIN season s ON s.id = cs.season_ref_id
    WHERE cs.season_id::text <> s.external_id;   -- 0 of 80

**Rename, not drop-and-add.** The column is renamed in place so the existing
FK values survive; an autogenerated DROP + ADD would empty a NOT NULL column.

The natural key moves with it: `UNIQUE (statsbomb_id, season_id)` on the two
integers becomes `UNIQUE (competition_id, season_id)` on the FKs, which
enforces the same invariant — one row per competition per season — against
the tables that own the source ids.

This step is allowed to change the public contract, unlike Phase 2: it removes
`statsbomb_id` and `season_id` from `CompetitionPublic`. Neither is read by the
frontend. The renamed FK is *not* added to the public model, so no field
changes type from int to uuid under a client's feet.
"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "3a71c4e9d052"
down_revision = "9f3f8d81b1e1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # The old integer natural key and its indexes go first: `season_id` must be
    # free before `season_ref_id` can take the name, and the index that shares
    # it must be gone before the FK's index can be renamed onto it.
    op.drop_constraint(
        "competition_season_statsbomb_id_season_id_key",
        "competition_season",
        type_="unique",
    )
    op.drop_index("ix_competition_season_season_id", table_name="competition_season")
    op.drop_index("ix_competition_season_statsbomb_id", table_name="competition_season")
    op.drop_column("competition_season", "season_id")
    op.drop_column("competition_season", "statsbomb_id")

    op.alter_column(
        "competition_season", "season_ref_id", new_column_name="season_id"
    )
    op.execute(
        "ALTER INDEX ix_competition_season_season_ref_id "
        "RENAME TO ix_competition_season_season_id"
    )
    op.execute(
        "ALTER TABLE competition_season "
        "RENAME CONSTRAINT fk_competition_season_season_ref_id "
        "TO fk_competition_season_season_id"
    )

    op.create_unique_constraint(
        "competition_season_competition_id_season_id_key",
        "competition_season",
        ["competition_id", "season_id"],
    )


def downgrade() -> None:
    op.drop_constraint(
        "competition_season_competition_id_season_id_key",
        "competition_season",
        type_="unique",
    )
    op.execute(
        "ALTER TABLE competition_season "
        "RENAME CONSTRAINT fk_competition_season_season_id "
        "TO fk_competition_season_season_ref_id"
    )
    op.execute(
        "ALTER INDEX ix_competition_season_season_id "
        "RENAME TO ix_competition_season_season_ref_id"
    )
    op.alter_column(
        "competition_season", "season_id", new_column_name="season_ref_id"
    )

    # Added nullable, backfilled from the owning rows, then constrained — the
    # table is not empty, so NOT NULL cannot be declared up front.
    op.execute("ALTER TABLE competition_season ADD COLUMN statsbomb_id integer")
    op.execute("ALTER TABLE competition_season ADD COLUMN season_id integer")
    op.execute(
        "UPDATE competition_season cs SET "
        "statsbomb_id = c.external_id::integer, "
        "season_id = s.external_id::integer "
        "FROM competition c, season s "
        "WHERE c.id = cs.competition_id AND s.id = cs.season_ref_id"
    )
    op.execute(
        "ALTER TABLE competition_season "
        "ALTER COLUMN statsbomb_id SET NOT NULL, "
        "ALTER COLUMN season_id SET NOT NULL"
    )
    op.create_index(
        "ix_competition_season_statsbomb_id", "competition_season", ["statsbomb_id"]
    )
    op.create_index(
        "ix_competition_season_season_id", "competition_season", ["season_id"]
    )
    op.create_unique_constraint(
        "competition_season_statsbomb_id_season_id_key",
        "competition_season",
        ["statsbomb_id", "season_id"],
    )
