"""Add spec fields to competition match event add lineup frame360 tables

Revision ID: 551ae34afebc
Revises: fdc68c6b279d
Create Date: 2026-06-25 21:34:39.077130

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '551ae34afebc'
down_revision = 'fdc68c6b279d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('frame360',
    sa.Column('match_id', sa.Uuid(), nullable=False),
    sa.Column('event_statsbomb_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('visible_area', sa.JSON(), nullable=False),
    sa.Column('freeze_frame', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['soccer_match.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_frame360_event_statsbomb_id'), 'frame360', ['event_statsbomb_id'], unique=False)
    op.create_index(op.f('ix_frame360_match_id'), 'frame360', ['match_id'], unique=False)
    op.create_table('lineup',
    sa.Column('match_id', sa.Uuid(), nullable=False),
    sa.Column('team_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('statsbomb_player_id', sa.Integer(), nullable=False),
    sa.Column('player_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('player_nickname', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('jersey_number', sa.Integer(), nullable=False),
    sa.Column('country_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['soccer_match.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lineup_match_id'), 'lineup', ['match_id'], unique=False)
    op.add_column('competition', sa.Column('match_updated', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('competition', sa.Column('match_available', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('competition', sa.Column('match_updated_360', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('competition', sa.Column('match_available_360', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('event', sa.Column('timestamp', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    op.add_column('event', sa.Column('possession', sa.Integer(), nullable=True))
    op.add_column('event', sa.Column('possession_team_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('event', sa.Column('play_pattern_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('event', sa.Column('duration', sa.Float(), nullable=True))
    op.add_column('event', sa.Column('under_pressure', sa.Boolean(), nullable=True))
    op.add_column('event', sa.Column('off_camera', sa.Boolean(), nullable=True))
    op.add_column('event', sa.Column('out', sa.Boolean(), nullable=True))
    op.add_column('soccer_match', sa.Column('match_week', sa.Integer(), nullable=True))
    op.add_column('soccer_match', sa.Column('competition_stage_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('soccer_match', sa.Column('home_team_gender', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    op.add_column('soccer_match', sa.Column('away_team_gender', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    op.add_column('soccer_match', sa.Column('home_team_country_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('soccer_match', sa.Column('away_team_country_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('soccer_match', sa.Column('home_team_group', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('soccer_match', sa.Column('away_team_group', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('soccer_match', sa.Column('home_manager_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('soccer_match', sa.Column('away_manager_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('soccer_match', sa.Column('match_status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('soccer_match', sa.Column('last_updated', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('soccer_match', sa.Column('match_status_360', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('soccer_match', 'match_status_360')
    op.drop_column('soccer_match', 'last_updated')
    op.drop_column('soccer_match', 'match_status')
    op.drop_column('soccer_match', 'away_manager_name')
    op.drop_column('soccer_match', 'home_manager_name')
    op.drop_column('soccer_match', 'away_team_group')
    op.drop_column('soccer_match', 'home_team_group')
    op.drop_column('soccer_match', 'away_team_country_name')
    op.drop_column('soccer_match', 'home_team_country_name')
    op.drop_column('soccer_match', 'away_team_gender')
    op.drop_column('soccer_match', 'home_team_gender')
    op.drop_column('soccer_match', 'competition_stage_name')
    op.drop_column('soccer_match', 'match_week')
    op.drop_column('event', 'out')
    op.drop_column('event', 'off_camera')
    op.drop_column('event', 'under_pressure')
    op.drop_column('event', 'duration')
    op.drop_column('event', 'play_pattern_name')
    op.drop_column('event', 'possession_team_name')
    op.drop_column('event', 'possession')
    op.drop_column('event', 'timestamp')
    op.drop_column('competition', 'match_available_360')
    op.drop_column('competition', 'match_updated_360')
    op.drop_column('competition', 'match_available')
    op.drop_column('competition', 'match_updated')
    op.drop_index(op.f('ix_lineup_match_id'), table_name='lineup')
    op.drop_table('lineup')
    op.drop_index(op.f('ix_frame360_match_id'), table_name='frame360')
    op.drop_index(op.f('ix_frame360_event_statsbomb_id'), table_name='frame360')
    op.drop_table('frame360')
    # ### end Alembic commands ###
