"""index soccer_match.competition_id

Revision ID: 87e2e9cbdd6e
Revises: 87e65e37d56a
Create Date: 2026-08-07 22:42:48.852356

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '87e2e9cbdd6e'
down_revision = '87e65e37d56a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_soccer_match_competition_id'), 'soccer_match', ['competition_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_soccer_match_competition_id'), table_name='soccer_match')
    # ### end Alembic commands ###
