"""Add event table

Revision ID: fdc68c6b279d
Revises: 970a30281eff
Create Date: 2026-06-22 23:43:54.616149

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'fdc68c6b279d'
down_revision = '970a30281eff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('statsbomb_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('match_id', sa.Uuid(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('minute', sa.Integer(), nullable=False),
    sa.Column('second', sa.Integer(), nullable=False),
    sa.Column('type_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('team', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('player', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('location_x', sa.Float(), nullable=True),
    sa.Column('location_y', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('raw_event', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['soccer_match.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_statsbomb_id'), 'event', ['statsbomb_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_statsbomb_id'), table_name='event')
    op.drop_table('event')
    # ### end Alembic commands ###
