"""add data_source, raw columns, event match_id index

Revision ID: 87e65e37d56a
Revises: 3cfb9503c5b7
Create Date: 2026-08-06 22:15:48.701691

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '87e65e37d56a'
down_revision = '3cfb9503c5b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_source',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_source_key'), 'data_source', ['key'], unique=True)
    # The 'statsbomb' row itself is seeded by init_db(), not here, so there is
    # exactly one definition of it and it also covers a freshly created DB.

    # Nullable on purpose: NULL means "ingested before this column existed" and
    # is distinguishable from a captured-but-empty payload. JSONB rather than
    # the JSON that event.raw_event uses — these are new, so there is no reason
    # to inherit that type.
    op.add_column('competition', sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # Composite: every read of event is "one match's events in index order", so
    # the second column serves the ORDER BY as well as the lookup. Until now
    # match_id was unindexed entirely.
    op.create_index('ix_event_match_id_index', 'event', ['match_id', 'index'], unique=False)
    op.add_column('lineup', sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('soccer_match', sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('soccer_match', 'raw')
    op.drop_column('lineup', 'raw')
    op.drop_index('ix_event_match_id_index', table_name='event')
    op.drop_column('competition', 'raw')
    op.drop_index(op.f('ix_data_source_key'), table_name='data_source')
    op.drop_table('data_source')
    # ### end Alembic commands ###
