"""Add end_location_x/y to event

Revision ID: 80647ecb6d8e
Revises: b28544af579f
Create Date: 2026-07-31 02:02:28.306015

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '80647ecb6d8e'
down_revision = 'b28544af579f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('end_location_x', sa.Float(), nullable=True))
    op.add_column('event', sa.Column('end_location_y', sa.Float(), nullable=True))
    # ### end Alembic commands ###

    # Backfill end_location_x/y from raw_event for existing rows. Priority:
    # pass_end_location, then shot_end_location, then carry_end_location — only
    # the first two elements (x, y) are used; shot_end_location may include a
    # third (z) element which is discarded.
    # raw_event->'field' returns a JSON `null` literal (not SQL NULL) for
    # fields present with a null value, so NULLIF(...::jsonb, 'null'::jsonb)
    # is required to make COALESCE actually fall through to the next field.
    op.execute(
        """
        UPDATE event
        SET
            end_location_x = (
                COALESCE(
                    NULLIF((raw_event->'pass_end_location')::jsonb, 'null'::jsonb),
                    NULLIF((raw_event->'shot_end_location')::jsonb, 'null'::jsonb),
                    NULLIF((raw_event->'carry_end_location')::jsonb, 'null'::jsonb)
                )->>0
            )::float,
            end_location_y = (
                COALESCE(
                    NULLIF((raw_event->'pass_end_location')::jsonb, 'null'::jsonb),
                    NULLIF((raw_event->'shot_end_location')::jsonb, 'null'::jsonb),
                    NULLIF((raw_event->'carry_end_location')::jsonb, 'null'::jsonb)
                )->>1
            )::float
        WHERE COALESCE(
            NULLIF((raw_event->'pass_end_location')::jsonb, 'null'::jsonb),
            NULLIF((raw_event->'shot_end_location')::jsonb, 'null'::jsonb),
            NULLIF((raw_event->'carry_end_location')::jsonb, 'null'::jsonb)
        ) IS NOT NULL
        """
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'end_location_y')
    op.drop_column('event', 'end_location_x')
    # ### end Alembic commands ###
