"""Add pass_recipient to event

Revision ID: 3cfb9503c5b7
Revises: 80647ecb6d8e
Create Date: 2026-08-01 15:47:03.300160

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3cfb9503c5b7'
down_revision = '80647ecb6d8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('pass_recipient', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # ### end Alembic commands ###

    # Backfill from raw_event for existing rows. pass_recipient is a plain
    # JSON string (already flattened by statsbombpy), so ->> ("get as text")
    # is sufficient on its own — unlike the end_location backfill, there's
    # no multi-branch COALESCE here, so ->>'s built-in JSON-null-to-SQL-NULL
    # coercion is all that's needed.
    op.execute(
        "UPDATE event SET pass_recipient = raw_event->>'pass_recipient'"
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'pass_recipient')
    # ### end Alembic commands ###
