"""phase 2 competition split: competition x season -> edition

Revision ID: 51e565e16027
Revises: 978091516b84
Create Date: 2026-08-09 04:16:56.000000

Splits the old `competition` table — which was really an *edition*, one row per
(competition, season) — into the timeless `competition`, a `season`, and the
`competition_season` edition that joins them (§2.1). That is the 2NF fix from
§1.1: La Liga's name, country and gender were stored once per season, 18 times
over, because they depend on `statsbomb_id` alone rather than the whole key.

**Hand-written, not autogenerated, and that is load-bearing.** Autogenerate sees
the new timeless `competition` and the renamed `competition_season` as unrelated
tables and emits `DROP TABLE competition`. `Competition.matches` carries
`cascade_delete=True`, so that drop would take **3,961 matches and 1,365,934
events** with it (§6/B3). Nothing here deletes a row: the existing table is
RENAMED in place, so every id survives and `soccer_match`'s foreign key follows
the rename automatically.

Two hazards this migration has to step around:

1. **Index names are schema-scoped; constraint names are table-scoped.**
   `ALTER TABLE ... RENAME` renames neither. So the old `competition_pkey`,
   its unique key and its two `ix_` indexes must be renamed *before* the new
   `competition` table is created, or `CREATE TABLE` collides on
   `competition_pkey`. The NOT NULL constraints need no attention — those are
   per-table.

2. **The split is only lossless if the functional dependencies hold.** All
   three are asserted below and the migration aborts if any fails. They were
   verified clean on 2026-08-06 and re-verified on 2026-08-08 (24 competitions
   x 48 seasons across 80 editions), but a future ingest could break them, and
   silently picking a winner for "what is La Liga called" is exactly the kind
   of quiet data loss this plan exists to prevent.
"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "51e565e16027"
down_revision = "978091516b84"
branch_labels = None
depends_on = None


# (label, SQL returning a violation count)
_PREFLIGHT_ASSERTIONS = [
    (
        "statsbomb_id does not determine the competition's attributes",
        """
        SELECT count(*) FROM (
            SELECT statsbomb_id FROM competition GROUP BY statsbomb_id
            HAVING count(DISTINCT (competition_name, country_name,
                                   competition_gender, competition_youth,
                                   competition_international)) > 1
        ) x
        """,
    ),
    (
        "season_id does not determine season_name",
        """
        SELECT count(*) FROM (
            SELECT season_id FROM competition GROUP BY season_id
            HAVING count(DISTINCT season_name) > 1
        ) x
        """,
    ),
    (
        "season_name maps to more than one season_id",
        """
        SELECT count(*) FROM (
            SELECT season_name FROM competition GROUP BY season_name
            HAVING count(DISTINCT season_id) > 1
        ) x
        """,
    ),
]


def _assert_split_is_lossless(bind) -> None:
    failures = []
    for label, sql in _PREFLIGHT_ASSERTIONS:
        violations = bind.execute(sa.text(sql)).scalar_one()
        if violations:
            failures.append(f"  - {label}: {violations} violation(s)")
    if failures:
        raise RuntimeError(
            "Refusing to split `competition`: the data no longer supports a "
            "lossless decomposition.\n"
            + "\n".join(failures)
            + "\nSplitting anyway would force an arbitrary choice about which "
            "value survives. Reconcile the conflicting rows first."
        )


def upgrade():
    bind = op.get_bind()
    _assert_split_is_lossless(bind)
    matches_before = bind.execute(sa.text("SELECT count(*) FROM soccer_match")).scalar_one()
    events_before = bind.execute(sa.text("SELECT count(*) FROM event")).scalar_one()

    # --- rename the edition table in place (no DELETE, no re-INSERT) ---------
    op.rename_table("competition", "competition_season")
    op.execute("ALTER INDEX competition_pkey RENAME TO competition_season_pkey")
    op.execute(
        "ALTER INDEX competition_statsbomb_id_season_id_key "
        "RENAME TO competition_season_statsbomb_id_season_id_key"
    )
    op.execute(
        "ALTER INDEX ix_competition_statsbomb_id "
        "RENAME TO ix_competition_season_statsbomb_id"
    )
    op.execute(
        "ALTER INDEX ix_competition_season_id RENAME TO ix_competition_season_season_id"
    )

    # --- point soccer_match at the edition by its true name ------------------
    op.alter_column(
        "soccer_match", "competition_id", new_column_name="competition_season_id"
    )
    op.execute(
        "ALTER INDEX ix_soccer_match_competition_id "
        "RENAME TO ix_soccer_match_competition_season_id"
    )
    op.execute(
        "ALTER TABLE soccer_match RENAME CONSTRAINT soccer_match_competition_id_fkey "
        "TO fk_soccer_match_competition_season_id"
    )

    # --- the timeless entities ----------------------------------------------
    op.create_table(
        "competition",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column(
            "external_id", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column(
            "country_name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.Column("gender", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("is_youth", sa.Boolean(), nullable=False),
        sa.Column("is_international", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"], ["data_source.id"], name="fk_competition_source_id_data_source"
        ),
        sa.PrimaryKeyConstraint("id", name="competition_pkey"),
        sa.UniqueConstraint(
            "source_id", "external_id", name="uq_competition_source_ext"
        ),
    )
    op.create_index(op.f("ix_competition_name"), "competition", ["name"], unique=False)
    op.create_index(
        op.f("ix_competition_source_id"), "competition", ["source_id"], unique=False
    )

    op.create_table(
        "season",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column(
            "external_id", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"], ["data_source.id"], name="fk_season_source_id_data_source"
        ),
        sa.PrimaryKeyConstraint("id", name="season_pkey"),
        sa.UniqueConstraint("source_id", "external_id", name="uq_season_source_ext"),
    )
    op.create_index(op.f("ix_season_name"), "season", ["name"], unique=False)
    op.create_index(op.f("ix_season_source_id"), "season", ["source_id"], unique=False)

    # --- edition -> entity links (nullable through expand) -------------------
    op.add_column(
        "competition_season", sa.Column("competition_id", sa.Uuid(), nullable=True)
    )
    op.add_column(
        "competition_season", sa.Column("season_ref_id", sa.Uuid(), nullable=True)
    )
    op.create_index(
        op.f("ix_competition_season_competition_id"),
        "competition_season",
        ["competition_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_competition_season_season_ref_id"),
        "competition_season",
        ["season_ref_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_competition_season_competition_id",
        "competition_season",
        "competition",
        ["competition_id"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_competition_season_season_ref_id",
        "competition_season",
        "season",
        ["season_ref_id"],
        ["id"],
    )

    # --- §6/B3: prove nothing cascaded --------------------------------------
    matches_after = bind.execute(sa.text("SELECT count(*) FROM soccer_match")).scalar_one()
    events_after = bind.execute(sa.text("SELECT count(*) FROM event")).scalar_one()
    if (matches_after, events_after) != (matches_before, events_before):
        raise RuntimeError(
            "Aborting: row counts changed during a migration that only renames "
            f"and adds. soccer_match {matches_before} -> {matches_after}, "
            f"event {events_before} -> {events_after}. This is the cascade "
            "described in §6/B3."
        )


def downgrade():
    op.drop_constraint(
        "fk_competition_season_season_ref_id", "competition_season", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_competition_season_competition_id", "competition_season", type_="foreignkey"
    )
    op.drop_index(
        op.f("ix_competition_season_season_ref_id"), table_name="competition_season"
    )
    op.drop_index(
        op.f("ix_competition_season_competition_id"), table_name="competition_season"
    )
    op.drop_column("competition_season", "season_ref_id")
    op.drop_column("competition_season", "competition_id")

    op.drop_index(op.f("ix_season_source_id"), table_name="season")
    op.drop_index(op.f("ix_season_name"), table_name="season")
    op.drop_table("season")

    op.drop_index(op.f("ix_competition_source_id"), table_name="competition")
    op.drop_index(op.f("ix_competition_name"), table_name="competition")
    # Dropped before the rename below, so the name is free again.
    op.drop_table("competition")

    op.execute(
        "ALTER TABLE soccer_match RENAME CONSTRAINT fk_soccer_match_competition_season_id "
        "TO soccer_match_competition_id_fkey"
    )
    op.execute(
        "ALTER INDEX ix_soccer_match_competition_season_id "
        "RENAME TO ix_soccer_match_competition_id"
    )
    op.alter_column(
        "soccer_match", "competition_season_id", new_column_name="competition_id"
    )

    op.execute(
        "ALTER INDEX ix_competition_season_season_id RENAME TO ix_competition_season_id"
    )
    op.execute(
        "ALTER INDEX ix_competition_season_statsbomb_id "
        "RENAME TO ix_competition_statsbomb_id"
    )
    op.execute(
        "ALTER INDEX competition_season_statsbomb_id_season_id_key "
        "RENAME TO competition_statsbomb_id_season_id_key"
    )
    op.execute("ALTER INDEX competition_season_pkey RENAME TO competition_pkey")
    op.rename_table("competition_season", "competition")
