/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSoccerRouteImport } from './routes/_layout/soccer'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutSoccerIndexRouteImport } from './routes/_layout/soccer/index'
import { Route as LayoutSoccerMatchesRouteImport } from './routes/_layout/soccer/matches'
import { Route as LayoutSoccerLineupsRouteImport } from './routes/_layout/soccer/lineups'
import { Route as LayoutSoccerIngestRouteImport } from './routes/_layout/soccer/ingest'
import { Route as LayoutSoccerEventsRouteImport } from './routes/_layout/soccer/events'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSoccerRoute = LayoutSoccerRouteImport.update({
  id: '/soccer',
  path: '/soccer',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSoccerIndexRoute = LayoutSoccerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutSoccerRoute,
} as any)
const LayoutSoccerMatchesRoute = LayoutSoccerMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => LayoutSoccerRoute,
} as any)
const LayoutSoccerLineupsRoute = LayoutSoccerLineupsRouteImport.update({
  id: '/lineups',
  path: '/lineups',
  getParentRoute: () => LayoutSoccerRoute,
} as any)
const LayoutSoccerIngestRoute = LayoutSoccerIngestRouteImport.update({
  id: '/ingest',
  path: '/ingest',
  getParentRoute: () => LayoutSoccerRoute,
} as any)
const LayoutSoccerEventsRoute = LayoutSoccerEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => LayoutSoccerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/settings': typeof LayoutSettingsRoute
  '/soccer': typeof LayoutSoccerRouteWithChildren
  '/soccer/events': typeof LayoutSoccerEventsRoute
  '/soccer/ingest': typeof LayoutSoccerIngestRoute
  '/soccer/lineups': typeof LayoutSoccerLineupsRoute
  '/soccer/matches': typeof LayoutSoccerMatchesRoute
  '/soccer/': typeof LayoutSoccerIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/soccer/events': typeof LayoutSoccerEventsRoute
  '/soccer/ingest': typeof LayoutSoccerIngestRoute
  '/soccer/lineups': typeof LayoutSoccerLineupsRoute
  '/soccer/matches': typeof LayoutSoccerMatchesRoute
  '/soccer': typeof LayoutSoccerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/soccer': typeof LayoutSoccerRouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/soccer/events': typeof LayoutSoccerEventsRoute
  '/_layout/soccer/ingest': typeof LayoutSoccerIngestRoute
  '/_layout/soccer/lineups': typeof LayoutSoccerLineupsRoute
  '/_layout/soccer/matches': typeof LayoutSoccerMatchesRoute
  '/_layout/soccer/': typeof LayoutSoccerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/settings'
    | '/soccer'
    | '/soccer/events'
    | '/soccer/ingest'
    | '/soccer/lineups'
    | '/soccer/matches'
    | '/soccer/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/settings'
    | '/'
    | '/soccer/events'
    | '/soccer/ingest'
    | '/soccer/lineups'
    | '/soccer/matches'
    | '/soccer'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/settings'
    | '/_layout/soccer'
    | '/_layout/'
    | '/_layout/soccer/events'
    | '/_layout/soccer/ingest'
    | '/_layout/soccer/lineups'
    | '/_layout/soccer/matches'
    | '/_layout/soccer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/soccer': {
      id: '/_layout/soccer'
      path: '/soccer'
      fullPath: '/soccer'
      preLoaderRoute: typeof LayoutSoccerRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/soccer/': {
      id: '/_layout/soccer/'
      path: '/'
      fullPath: '/soccer/'
      preLoaderRoute: typeof LayoutSoccerIndexRouteImport
      parentRoute: typeof LayoutSoccerRoute
    }
    '/_layout/soccer/matches': {
      id: '/_layout/soccer/matches'
      path: '/matches'
      fullPath: '/soccer/matches'
      preLoaderRoute: typeof LayoutSoccerMatchesRouteImport
      parentRoute: typeof LayoutSoccerRoute
    }
    '/_layout/soccer/lineups': {
      id: '/_layout/soccer/lineups'
      path: '/lineups'
      fullPath: '/soccer/lineups'
      preLoaderRoute: typeof LayoutSoccerLineupsRouteImport
      parentRoute: typeof LayoutSoccerRoute
    }
    '/_layout/soccer/ingest': {
      id: '/_layout/soccer/ingest'
      path: '/ingest'
      fullPath: '/soccer/ingest'
      preLoaderRoute: typeof LayoutSoccerIngestRouteImport
      parentRoute: typeof LayoutSoccerRoute
    }
    '/_layout/soccer/events': {
      id: '/_layout/soccer/events'
      path: '/events'
      fullPath: '/soccer/events'
      preLoaderRoute: typeof LayoutSoccerEventsRouteImport
      parentRoute: typeof LayoutSoccerRoute
    }
  }
}

interface LayoutSoccerRouteChildren {
  LayoutSoccerEventsRoute: typeof LayoutSoccerEventsRoute
  LayoutSoccerIngestRoute: typeof LayoutSoccerIngestRoute
  LayoutSoccerLineupsRoute: typeof LayoutSoccerLineupsRoute
  LayoutSoccerMatchesRoute: typeof LayoutSoccerMatchesRoute
  LayoutSoccerIndexRoute: typeof LayoutSoccerIndexRoute
}

const LayoutSoccerRouteChildren: LayoutSoccerRouteChildren = {
  LayoutSoccerEventsRoute: LayoutSoccerEventsRoute,
  LayoutSoccerIngestRoute: LayoutSoccerIngestRoute,
  LayoutSoccerLineupsRoute: LayoutSoccerLineupsRoute,
  LayoutSoccerMatchesRoute: LayoutSoccerMatchesRoute,
  LayoutSoccerIndexRoute: LayoutSoccerIndexRoute,
}

const LayoutSoccerRouteWithChildren = LayoutSoccerRoute._addFileChildren(
  LayoutSoccerRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutSoccerRoute: typeof LayoutSoccerRouteWithChildren
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutSoccerRoute: LayoutSoccerRouteWithChildren,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
